---
version: '3'
services:
  worker:
    build: .
    image: deeplearninc/a2ml
    command: wait-for-it rabbitmq:5672 -t 30 -- celery -A a2ml.tasks_queue.celery_app worker --loglevel=info
    env_file: develop.env
    volumes:
      - .:/app
    depends_on:
      - minio
      - rabbitmq

  minio:
    image: minio/minio:RELEASE.2020-03-14T02-21-58Z
    command: server --compat /data
    ports:
      - 9000:9000
    volumes:
      - ./tmp/data/:/data/
    env_file: develop.env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
