---
version: '3'
services:
  tests:
    build: .
    image: deeplearninc/a2ml
    working_dir: /app
    command: wait-for-it rabbitmq:5672 -t 30 -- tox
    env_file: develop.env
    depends_on:
      - worker

  worker:
    build: .
    image: deeplearninc/a2ml
    command: wait-for-it rabbitmq:5672 -t 30 -- celery -A a2ml.tasks_queue.celery_app worker --loglevel=info
    env_file: develop.env
    depends_on:
      - createbucket
      - rabbitmq

  minio:
    image: minio/minio:RELEASE.2020-03-14T02-21-58Z
    command: server --compat /data
    ports:
      - 9000:9000
    env_file: develop.env
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9000" ]
      interval: 5s
      timeout: 5s
      retries: 10

  createbucket:
    image: minio/mc
    depends_on:
      - minio
    env_file: develop.env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 secret strongsecret;
      /usr/bin/mc rm -r --force myminio/sample-bucket;
      /usr/bin/mc mb myminio/sample-bucket;
      /usr/bin/mc policy set upload myminio/sample-bucket;
      /usr/bin/mc cp /data/iris.csv myminio/sample-bucket/workspace/projects/a2ml-app/files/;
      exit 0;
      "

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 5s
      retries: 10
