---
version: '3'
services:
  a2ml:
    build: .
    image: deeplearninc/a2ml
    working_dir: /app
    command: pytest -vv -s -o log_cli=True -o log_cli_level=info -W ignore tests/test_celery_tasks/test_tasks.py::TestTasks::test_train
    env_file: develop.env
    volumes:
      - .:/app
    depends_on:
      - a2ml-worker

  a2ml-worker:
    build: .
    image: deeplearninc/a2ml
    command: celery -A a2ml.tasks_queue.celery_app worker --loglevel=info
    env_file: develop.env
    volumes:
      - .:/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
