---
version: '3'
services:
  a2ml:
    build: .
    image: deeplearninc/a2ml
    working_dir: /app
    command: pytest -vv -s -o log_cli=True -o log_cli_level=info -W ignore tests/test_celery_tasks/test_tasks.py::TestTasks::test_import
    env_file: develop.env
    volumes:
      - .:/app
    depends_on:
      - a2ml-worker

  a2ml-worker:
    build: .
    image: deeplearninc/a2ml
    command: celery -A a2ml.tasks_queue.celery_app worker --loglevel=info
    env_file: develop.env
    volumes:
      - .:/app
    depends_on:
      - minio
      - redis

  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    command: server --compat /data
    ports:
      - 9000:9000
    volumes:
      - ./tmp/data/:/data/
    env_file: develop.env
    
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    command: redis-server --save "" --appendonly no

volumes:
  redis_data:
  node_modules:
