version: 2.1
jobs:
  build-docs:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install .[docs]
      - run:
          name: Build docs
          command: cd docs/ && make html
      - persist_to_workspace:
          root: docs/build
          paths: html
  deploy-docs:
    docker:
      - image: node:10.15.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/build
      - run:
          name: Disable jekyll builds
          command: touch docs/build/html/.nojekyll
      - add_ssh_keys:
          fingerprints: "44:aa:23:95:60:12:6b:b5:8d:b2:e5:05:24:1f:94:cf"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            git config user.email "23641280+augerbot@users.noreply.github.com"
            git config user.name "augerbot"
            npm install -g --silent gh-pages@2.2.0
            gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/build/html
  build-test:
    parameters:
      python_version:
        default: "3.7"
        type: string
    working_directory: ~/a2ml
    docker:
      - image: circleci/python:<< parameters.python_version >>
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python<< parameters.python_version >>/site-packages
      - restore_cache:
          key: a2ml-{{ arch }}-<< parameters.python_version >>-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - save_cache:
          key: a2ml-{{ arch }}-<< parameters.python_version >>-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python<< parameters.python_version >>/site-packages"
      # TODO: Fix flake8 issues
      # - run:
      #     command: |
      #       pipenv run python setup.py flake8
      - run: pipenv run python setup.py test

  deploy:
    working_directory: ~/a2ml
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: a2ml-{{ arch }}-3.7-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run: pipenv run python setup.py verify
      - run:
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run: pipenv run python setup.py bdist_wheel
      - run:
          command: |
            sudo pip install twine
            echo "Deploying new package to pypi.org..."
            twine upload dist/*

workflows:
  build_and_deploy_docs:
    jobs:
      - build-docs
      - deploy-docs:
          name: deploy3.7
          requires:
            - build-docs
          filters:
            branches:
              only:
                - master
  commit:
    jobs:
      - build-test:
          name: build3.7
          python_version: "3.7"
  build_and_deploy:
    jobs:
      - build-test:
          name: build3.6
          python_version: "3.7"
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-test:
          name: build3.7
          python_version: "3.7"
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build3.7
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
