# Overall project name
name: my_app
# List of providers: auger, google, azure
providers:
# Local file name or remote url to the data source file
source:
# List of columns to be excluded from the training data
exclude:
# Target column name
target:
# Model type: classification|regression|timeseries
model_type:
# Experiment settings
experiment:
  # Number of folds used for k-folds validation of individual trial
  cross_validation_folds: 5
  # Maximum time to run experiment in minutes
  max_total_time: 60
  # Maximum time to run individual trial in minutes
  max_eval_time: 5
  # Maximum trials to run to complete experiment
  max_n_trials: 10
  # Try to improve model performance by creating ensembles from the trial models
  use_ensemble: true

  metric: r2
  # Path to validation dataset
  #validation_data: