---
# list of providers
providers: [auger]

source: ../iris.csv
exclude: []
target: 'species'
# Model type: classification|regression|timeseries
model_type: classification
# source: https://www.openml.org/data/download/8/dataset_8_liver-disorders.arff
# exclude:
# target:
# model_type: 'classification'
