---
# List of providers: auger, google, azure
providers: auger
# Local file name or remote url to the data source file
source:
# List of columns to be excluded from the training data
exclude:
# Target column name
target:
# Model type: classification|regression|timeseries
model_type: classification
# overall experiment time budget in minutes (default of 1 hour)
budget: 60