budget: 3600
dataset_id: TBL4772768869943083008
exclude: Team,League,Year
metric: MINIMIZE_MAE
name: moneyball
project: automl-test-237311
providers: AZ
region: us-central1
source: gs://moneyball/baseball.csv
target: RS
azure_region: 'East US 2'
azure_resource_group: autoautoml
azure_compute_name: autoautoml
