budget: 3600
dataset_id: TBL4772768869943083008
exclude: Team,League,Year
metric: MINIMIZE_MAE
name: moneyball
project: automl-test-237311
providers: AZ
region: us-central1
source: gs://moneyball/baseball.csv
target: RS
azure_compute_name: a2ml
azure_region: eastus2
azure_resource_group: autoautoml
azure_metric: spearman_correlation
azure_source: https://storage.cloud.google.com/moneyball/baseball.csv?folder&organizationId=465405141758&_ga=2.120546504.-1320989109.1554983622
